import React from 'react'


export const metadata = {
    title: "User Profile",
    description: "Generated by create next app",
  };

export default function page({params}) {
    console.log(params);
    
  return (
    <div>User profile page  </div>
  )
}
